---
format: revealjs
---

# Git internals {#git_internals}

## Was passiert in Git?

Vorbereitungen

::::::: columns
:::: column
::: fragment
[Version 1]{.smaller}
``` bash
mkdir demo
cd demo
git init
git branch -m main
```
:::
::::

:::: column
::: fragment
[Version 2]{.smaller}
``` bash
git init demo
cd demo
git branch -m main
```
:::
::::
:::::::


:::{.notes}
Neues Repo anlegen - DEMO
Kann man nicht oft genug machen 
Keine konsistente Namensgebung im Kurs erwarten!
:::


## Git - Ordner

[Darstellen der Ordnerstruktur durch *tree* erfordert Nachinstallation!]{.smaller}


::: {.fragment}
:::{.smaller}
-   <http://gnuwin32.sourceforge.net/packages/tree.htm>
-   Zip herunterladen
-   Ordner `c:\benutzer\name\bin` erstellen
-   Zip dort entpacken
:::
:::

:::{.notes}
TREE installieren
:::

---

### Git Ordner inspizieren

``` bash
tree .git 
```

``` bash
.git
├── branches
├── config
├── description
├── HEAD
├── hooks
│   ├── applypatch-msg.sample
│   ├── commit-msg.sample
│   ├── fsmonitor-watchman.sample
│   ├── post-update.sample
│   ├── pre-applypatch.sample
│   ├── pre-commit.sample
│   ├── pre-merge-commit.sample
│   ├── prepare-commit-msg.sample
│   ├── pre-push.sample
│   ├── pre-rebase.sample
│   ├── pre-receive.sample
│   ├── push-to-checkout.sample
│   ├── sendemail-validate.sample
│   └── update.sample
├── info
│   └── exclude
├── objects
│   ├── info
│   └── pack
└── refs
    ├── heads
    └── tags
```

:::{.notes}
* versteckte Datei
* So sieht leeres Repo aus
* Man sieht HEAD => genauerer Blick!
:::

---

### Inhalt hinzufügen

::: fragment
``` bash
echo "Etwas HTML" >> homepage.html
git add homepage.html
```
:::

::: fragment
und wieder `tree  .git`
:::


:::{.notes}
* Datei anlegen und adden
* dann wieder tree
:::

---

Neue Inhalte:

``` bash
.git
├── branches
├── config
├── description
├── HEAD
├── hooks
│   ├── applypatch-msg.sample
│   ├── commit-msg.sample
│   ├── fsmonitor-watchman.sample
│   ├── post-update.sample
│   ├── pre-applypatch.sample
│   ├── pre-commit.sample
│   ├── pre-merge-commit.sample
│   ├── prepare-commit-msg.sample
│   ├── pre-push.sample
│   ├── pre-rebase.sample
│   ├── pre-receive.sample
│   ├── push-to-checkout.sample
│   ├── sendemail-validate.sample
│   └── update.sample
├── index    <<< Nicht direkt lesbar
├── info
│   └── exclude
├── objects
│   ├── ce   <<< Inhalt von homepage.html
│   │   └── 1332fcf1795166c3c5cd0216b5e7dc2dce7998
│   ├── info
│   └── pack
└── refs
    ├── heads
    └── tags
```


:::{.notes}
* Abweichende Hashes!!!!
* CE als Ordner
* Versuchen in die Datei zu sehen bringt nichts!
:::

---

Nicht direkt lesbar

[Datei *index* = Stage]{.smaller}

::: fragment
``` bash
git ls-files --stage 
```
:::

<br>

::: fragment
``` bash
100644 ce1332fcf1795166c3c5cd0216b5e7dc2dce7998 0 homepage.html
```
:::

::: notes
Wir entfernen uns von den Std Befehlen!

"ce" bildet einen Ordner im Tree\
Dateityp 100664\
Status 0
:::

---

Direktanzeige des Hashs der Datei:

::: fragment
``` bash
git hash-object homepage.html

# Ausgabe 
ce1332fcf1795166c3c5cd0216b5e7dc2dce7998
```
:::

---

Commiten der Hompage

``` bash
git commit -m "homepage.html added"
```

[Wieder `tree .git`]{.smaller}

``` bash
.git
├── branches
├── COMMIT_EDITMSG
├── config
├── description
├── HEAD
├── hooks
...
├── index
├── info
│   └── exclude
├── logs
│   ├── HEAD
│   └── refs
│       └── heads
│           └── main
├── objects
│   ├── 66
│   │   └── 732ba22bd6f2cedd2ddbe2b289a03ce033ef06
│   ├── 94
│   │   └── eed25c4ef6cfa1384df66f28308c09dc9bf28d
│   ├── ce
│   │   └── 1332fcf1795166c3c5cd0216b5e7dc2dce7998
│   ├── info
│   └── pack
└── refs
    ├── heads
    │   └── main
    └── tags
```

::: notes
NICHT SOFORT MACHEN wegen VLG mit Folie  
Einige Änderungen - suchen lassen  

Objects und logs und refs
:::

---

### Objects

In der Ausgabe von *tree*

``` bash
├── objects
│   ├── 71
│   │   └── df20d4a14e84f6f1dc12737731afba85415171
│   ├── 94
│   │   └── eed25c4ef6cfa1384df66f28308c09dc9bf28d
│   ├── ce
│   │   └── 1332fcf1795166c3c5cd0216b5e7dc2dce7998
```

``` bash
git log 

# Ausgabe 
commit 71df20d4a14e84f6f1dc12737731afba85415171 (HEAD -> main)
Author: wolfgang <hoeferwolf@t-online.de>
Date: Sun Jan 26 20:20:10 2025 +0100
      homepage.html added
```

:::{.notes}
Wo sehen wir den obersten Hash?  
log aufrufen => commit
:::

---

Überprüfen des Verdachts ... nur Bestätigung

``` bash
git cat-file -t 71df20d4a14e84f6f1dc12737731afba85415171   
# -t = Typ

# Ausgabe 
commit
```

:::{.notes}
Alternativer Weg
t steht für Typ
:::

---

Mehr Details

``` bash
# Eingabe
git cat-file -p 71df20d4a14e84f6f1dc12737731afba85415171
# -p = pretty

# Ausgabe
tree 94eed25c4ef6cfa1384df66f28308c09dc9bf28d  << wichtig!
author wolfgang <hoeferwolf@t-online.de> 1737919210 +0100
committer wolfgang <hoeferwolf@t-online.de> 1737919210 +0100
homepage.html added
```

::: smaller
Der Commit verweist auf einen TREE (hier nur eine einzige Datei!)
:::

``` bash
git cat-file -t 94eed25c4ef6cfa1384df66f28308c09dc9bf28d

# Ausgabe 
tree
```

:::{.notes}
Details des Commit anzeigen (p = pretty)
t-Ausgabe vom Tree-Hash als Kontrolle  
Aber was ist ein Tree?
:::

---

Inhalt des Trees

``` bash
# Eingabe
git cat-file -p 94eed25c4ef6cfa1384df66f28308c09dc9bf28d

# Ausgabe - normal deutlich länger, da mehr Dateien!
100644 blob ce1332fcf1795166c3c5cd0216b5e7dc2dce7998 homepage.html
```

*blob* = Inhalt von *homepage.html*

:::{.notes}
Inhalt vom Tree ist eine Info über einen BLOB (Binary Large Object)  
Also der Link Inhalt <-> Dateiname, getrennte Speicherung!
:::

---

Der Blob enthält:

``` bash
git cat-file -p ce1332fcf1795166c3c5cd0216b5e7dc2dce7998

# Ausgabe
Etwas HTML
```

:::{.notes}
Was steht im BLOB?
:::

---

Zusammenfassung

-   Der Commit zeigt auf einen Tree
-   Im Tree stehen Dateinamen mit den Hashes\
    Das sind nur die Namen und nicht die Dateien!
-   Der Hash gehört zu einem blob (oder weiterem tree),\
    also den reinen Rohdaten der Datei ohne Dateinamen

::: notes
Jeder Commit ist ein Tree

Das spart Speicher, da mehrere Trees (=Commits) auf\
unveränderte Rohdaten verweisen können.
:::