---
format: revealjs
---

## Hands On 2 {#handson_II}

Erstellen / Nacherstellen zweier „Kurzgeschichten“.

## Idee

Repository I: Meine Vorlage

Repository II: Euer Buch

::: {.notes}
Verweis auf Materialordner PDF
:::

## Vorsicht

Der Entwicklungszyklus ist sehr exakt ausgearbeitet, um bestimmte Situationen zu erzeugen. Also wirklich jeden Schritt *genau so* machen, wie beschrieben!

``` bash
git log --oneline

# Ausgabe 
* b1d90b7 (HEAD -> main, tag: Step_6) Story2 ß->s
* 728a5a4 (tag: Step_5) Idee2
* 2a95c37 (tag: Step_4) Idee1
* 742f590 (tag: Step_3) Story 2 begonnen
* 0ab5c1e (tag: Step_2) Story_1 komplett
* 8d9c6ac (tag: Step_1) Story_1 Teil1
```

## Vorbereitung

::: fragment
Erstellen eines Arbeitsordners, z.B.

``` bash
mkdir hands_on_ii
cd hands_on_ii
```
:::

::: fragment
Clonen des Vorlagen-Repositories

``` bash
git clone xxx.xxx.xxx
```
:::

## Vorbereitung

::: fragment
Erstellen des Buch-Repositories

``` bash
git init buch
cd buch
git branch -m main
```
:::

## Arrangieren der Fenster

::::::: columns
:::: column
::: fragment
**Terminal 1**\
Vorlagen Repository

``` bash
cd hands_on_ii
cd vorlage
```
:::
::::

:::: column
::: fragment
**Terminal 2**\
Buch Repository

``` bash
cd hands_on_ii
cd buch
```
:::
::::
:::::::

## Story 1 - Teil 1

[(Vorlage-Ordner/Fenster)]{.smaller}

::: fragment
Den ersten Entwicklungsstand (Projektbeginn) auschecken

``` bash
git checkout Step_1
```
:::

::: fragment
Kopieren von `story_1.md` in den Buch-Ordner

``` bash
cp story_1.md ../buch
```
:::

---

### Aktueller Stand 
[(Buch-Ordner/Fenster)]{.smaller}

Die erste Hälfte von Story 1 ist *geschrieben*.  
Kurzer Blick in die Geschichte, um Orientierung zu bekommen:

``` bash
less story_1.md

# beenden mit 'q'
```

---

### Versionieren

Status prüfen

``` bash
git status
```

Ausgabe:

``` bash
Auf Branch main 

Noch keine Commits

Unversionierte Dateien:
  (benutzen Sie "git add <Datei>...", 
   um die Änderungen zum Commit vorzumerken)
    story1.md 

nichts zum Commit vorgemerkt, aber es gibt unversionierte Dateien
(benutzen Sie "git add" zum Versionieren) 
```

---

### Versionieren

``` bash
git add .
git status 

# Ausgabe 
Auf Branch main
Noch keine Commits
Zum Commit vorgemerkte Änderungen:
  (benutzen Sie "git rm --cached <Datei>..."
  zum Entfernen aus der Staging-Area)
  neue Datei:
      story1.md
```

## Story 1 - Teil 2

[(Vorlage-Ordner/Fenster)]{.smaller}

::: fragment
Step 2 auschecken

``` bash
git checkout Step_2
```
:::

::: fragment
Übertragen in den Buch Ordner

``` bash
cp story_1.md ../buch
```
:::

---

### Status-Check

::: fragment
``` bash
# Ausgabe
Auf Branch main
Noch keine Commits
Zum Commit vorgemerkte Änderungen:
  (benutzen Sie "git rm --cached <Datei>..."
   zum Entfernen aus der Staging-Area)
   neue Datei:  story1.md

Änderungen, die nicht zum Commit vorgemerkt sind:
  (benutzen Sie "git add <Datei>...",
   um die Änderungen zum Commit vorzumerken)
   (benutzen Sie "git restore <Datei>...", um die Änderungen im
    Arbeitsverzeichnis zu verwerfen)
    geändert:  story1.md
```
:::

---

### Versionieren

Kurzer Blick in die Geschichte

::: fragment
``` bash
less story_1.qmd

# beenden mit 'q'
```
:::

::: {.fragment}
``` bash
git add .
git commit -m 'Guter Ansatz'

# Ausgabe 
[main (Root-Commit) 5229c6b] Guter Ansatz
1 file changed, 4 insertions(+)
create mode 100644 story1.md
```
:::



## Story 2 - Planung
[Buch Fenster]{.smaller}

Branch erstellen

``` bash
git switch -c entwicklung_story_2
```

## Story 2 - Teil 1
[Vorlage Fenster]{.smaller}

::: fragment
Step 3 auschecken

``` bash
git checkout Step_3
```
:::

::: fragment
Kopieren Story 2 Teil 1

``` bash
cp story_2.md ../buch/
```
:::

---

### Versionieren
[Buch Fenster]{.smaller}

Blick ins Buch

``` bash
less story_2.md
```

::: fragment
Für gut befunden ...

``` bash
git add story2.md
git commit -m "Story 2 begonnen"
```
:::

::: fragment
Schaffenskrise - which way?

``` bash
git switch -c story2_idee_1
git switch -c story2_idee_2
```
:::

## Verfolgen von Idee 1
[Buch Fenster]{.smaller}

Beginnen mit Idee 1

::: fragment
Richtigen Branch wählen (BUCH)

``` bash
git switch story2_idee_1
```
:::

::: fragment
Step 4 auschecken und kopieren [(VORLAGE)]{.alert}

``` bash
git checkout Step_4
cp story_2.md ../buch
```
:::

---

### Versionieren
[Buch Fenster]{.smaller}

::: fragment
Blick ins Buch

``` bash
less story2.md
```
:::

::: fragment
Versionieren

``` bash
git add story2.md
git commit-m "Inhalt nach Idee1 fortgeführt"
```
:::

## Story 2 - Idee 2
[Buch Fenster]{.smaller}

::: fragment
Wechsel in richtigen Branch

``` bash
git switch story2_idee_2
```
:::

::: fragment
Ausarbeiten von Idee 2 [(VORLAGE)]{.alert}

``` bash
git checkout Step_5
cp story2.md ../buch/
```
:::

::: fragment
Versionieren [(BUCH)]{.alert}

``` bash
git add story2.md
git commit -m "Inhalt nach Idee 2 fortgeführt"
```
:::

---

### Versions-Chaos
[Buch Fenster]{.smaller}

1.  *story2.md* im Branch entwicklung_story_2
2.  *story2.md* im Branch story_2_idee_1
3.  *story2.md* im Branch story_2_idee_2

---

## Orientieren / Reparieren

---

### Schreibfehler

Im Branch [entwicklung_story_2]{.branch}:

„[weiße]{.alert} Schildkröte“ wird zu „[weise]{.success} Schildkröte“

[Nicht in einem Ideen-Branch ausführen!]{.alert .smaller}

``` bash
git switch entwicklung_story_2
```
::: {.columns}
::: {.column}
::: fragment
[Vorlage Fenster]{.smaller}
```bash
git checkout Step_6
cp story2.md ../buch/
```
:::
:::
::: {.column}
::: fragment
[Buch Fenster]{.smaller}
```bash
git diff # Workdir gegen Stage
```
:::
::: {.fragment}
```bash
Freddy war nicht allein. Seine beste Freundin,
-Shelly, die weiße Schildkröte, lebte ebenfalls am  # alt 
+Shelly, die weise Schildkröte, lebte ebenfalls am  # neu
```
:::
::: {.fragment}
```bash
git add story2.md
git commit -m "typo 'weiße' korrigiert"
```
:::
:::
:::
<!-- end columns -->



::: fragment
[Die Änderung erreicht die Ideen-Branches **nicht**!]{.quadrant3}
:::

## Idee 1 gewinnt

::: {.fragment}
[Mergen von Branch [Idee 1]{.branch} auf [Entwicklung]{.branch}]{.smaller}
:::

::: fragment
Unterschiede Checken

``` bash
git diff story2_idee_1..HEAD # Idee 1 gegen Entwicklung 
```
:::

::: fragment
Problem Rechtschreibfehler

``` bash
...
Freddy war nicht allein. Seine beste Freundin,
-Shelly, die weiße Schildkröte, lebte ebenfalls am  # alt 
+Shelly, die weise Schildkröte, lebte ebenfalls am  # neu
...
```
:::

---

### Merge

::: fragment
``` bash
* b6cd137 (HEAD -> entwicklung_story_2) ß->S
| * 9fef27a (story2_idee_1) Inhalt nach Idee1 fortgeführt
|/  
| * 38fdb9f (story2_idee_2) Inhalt nach Idee 2 fortgeführt
|/  
* 2beb0f8 (main) Story 2 begonnen
* 9fc3bf6 Guter Ansatz
```
:::

::: fragment
Ein FF-Merge ist nicht möglich.\
Ein Merge-Commit ist nötig.
:::

::: notes
``` bash
git diff --color-words entwicklung_story_2..story2_idee_1
```

Vergleich der Commits: weiseweiße
:::

## Schritt 15

**Weitere Änderung**

::: fragment
Die Schildkröte soll eine Riesenschildkröte werden!  
Änderung im Branch *story2_idee_1* vornehmen.
:::

::: fragment
``` bash
git switch story2_idee_1 
sed -i s/Schildkröte/Riesenschildkröte/g story2.md 
```
:::

::: notes
``` bash
git diff --color-words entwicklung_story_2..story2_idee_1
```

Was sehen wir? Keine Neuerung, da Änderung nicht im Commit!

Wir brauchen `git diff`
:::

## Schritt 16

Commiten der Version

::: fragment
``` bash
git add story2.md
git commit -m "Riesenschildkröte statt Schildkröte"
```
:::

::: fragment
``` bash
git diff --color-words entwicklung_story_2..story2_idee_1

# Ausgabe
Freddy war nicht allein. Seine beste Freundin,
Shelly, die >>weise Schildkröte<<,**weiße Riesenschildkröte**, 
lebte ebenfalls am Teich. Shelly war für ihre ruhige und besonnene
Art bekannt, aber sie konnte auch sehr mutig sein,
wenn es darauf ankam.

```
:::

::: notes
Wieder den Commit - Vergleich

``` bash
git diff --color-words entwicklung_story_2..story2_idee_1
```

Entwicklung: WEISE schildkröte = Tier falsch\
Ideen: WEIßE riesenschildkröte = weiße falsch
:::

## Schritt 17

::: fragment
Merge von Idee auf Entwicklung
:::

::: fragment
``` bash
git switch entwicklung_story_2 
git merge story2_idee_1
```
:::

------------------------------------------------------------------------

Meldung

``` bash
automatischer Merge von story2.md
KONFLIKT (Inhalt): Merge-Konflikt in story2.md
Automatischer Merge fehlgeschlagen; beheben 
Sie die Konflikte und committen Sie dann das Ergebnis.
```

------------------------------------------------------------------------

Manuell korrigieren und wieder speichern

``` bash
Freddy war nicht allein. Seine beste Freundin,
<<<<<<< HEAD
Shelly, die weise Schildkröte, lebte ebenfalls am
=======
Shelly, die weiße Riesenschildkröte, lebte ebenfalls am
>>>>>>> story2_idee_1
Teich. Shelly war für ihre ruhige und besonnene
Art bekannt, aber sie konnte auch sehr mutig sein,
```