---
format: revealjs
---

# Arbeiten im Team{#team}

---

**Vorgehen**  

:::{.fragment}
Im Prinzip wie bei der lokalen Arbeit.
:::

:::{.fragment}
Zwischenstände werden geteilt.
:::

:::{.fragment}
Wo wird gearbeitet?
:::

:::{.fragment .smaller}

* Einfacher Git-Server (ssh)
* Kennwortloser http-git-server
* github / gitlab / gitea (bezahlt)
* Gemeinnützig, z.B. codeberg.org

(Selbst hosten)?
:::


# Server-Repository

---



Ein Server-Repository wird angelegt durch

```bash
git init --bare projekt
```

::: {.fragment}
[Dort werden von Benutzern keine Dateien erstellt!]{.smaller}

**Workflow**  
:::

::: {.fragment .smaller}
* Repository clonen (einmalig)
* Aktualisieren (pull -- regelmäßig)
* Veröffentlichen (push -- wenn sinnvoll)
:::


---

### Regeln  

::: {.fragment}
**Wichtig**

Firmen definieren ihre eigenen Workflows.

Es gibt kein *richtig* sondern nur Regeln.

Branching wird zentrales Thema!

:::

::: {.fragment}
**Neu: Clonen**  

Haben wir bereits gemacht (ohne Zugriffsrechte!)

Jetzt kompletter Setup!

:::

---

### ssh

[(secure shell - Verschlüsselter Remote Zugriff)]{.smaller}

[Mit SSH anmelden auf deinem Server]{.smaller}

```bash
ssh  benutzer@<IP>
# Kennwort gitkurs
```

[Falls abweichender Port:]{.smaller}

```bash
ssh -p 25 benutzer@<IP>
```

---

### Anlegen eines git Repos

```bash
cd /home/benutzer/
git init --bare projekt.git  # Endung wichtig
cd projekt.git 
git branch -m main 
```

::: {.fragment}
**Weitere Reihenfolge**

:::{.smaller}
* clonen
* Readme anlegen
* ersten Commit erstellen
* pushen

Danach können andere mit dem Repository arbeiten.
:::
:::

---

### Clonen

```bash
git clone benutzer@<IP>:/home/benutzer/projekt.git
cd projekt   # ohne ".git"
```

::: {.fragment}
[Bei abweichendem Port]{.smaller}

```bash
git clone ssh://<IP>:25/home/benutzer/projekt.git
cd projekt
```
:::

::: {.fragment}
[Generelle Kontrolle]{.smaller}

```bash
git remote -v 

# Ausgabe
origin	benutzer@<IP>:/home/benutzer/projekt.git (fetch)
origin	benutzer@<IP>:/home/benutzer/projekt.git (push)
```
:::

---

### Vorsicht

```bash
git status

# Ausgabe
Auf Branch master    <<<<<<<<< VORSICHT

Noch keine Commits

nichts zu committen (erstellen/kopieren Sie Dateien und benutzen
Sie "git add" zum Versionieren)
```

::: {.fragment}
### Umbenennen

```bash
git branch -m main 
```

:::

---

### Readme anlegen

```bash
echo "Willkommen ..." > README.txt
git add . 
git commit -m "Initial"
git push -u origin main
```

::: {.notes}

Hier kommt eine kleine Tree-Demo auf Server und Client

:::


## Blick ins Innere von git

Warum das Umbenennen?

```bash
git init --bare labor.git
cd labor 
tree 
```


Einzelschritte beobachten mit Tree auf Server und Client

```bash
sudo apt install tree -y
```

---

Aktueller Stand (Server)
```bash
.
├── branches
├── config
├── description
├── HEAD     <<<< Was steht hier??
├── hooks
│   ├── applypatch-msg.sample
...
├── info
│   └── exclude
├── objects
│   ├── info
│   └── pack
└── refs
    ├── heads    <<<< MERKEN
    └── tags
```

---

Aktueller Stand (Server)
```bash
cat HEAD 

# Ausgabe
ref: refs/heads/master
```

Aber kein Branch dieses Namens vorhanden!

```bash
└── refs
    ├── heads    <<<< kein "master"
    └── tags
```

---

Umbenennen  (Server)
```bash
git branch -m main 
```

Inhalt von HEAD 
```bash
cat HEAD 

# Ausgabe
ref: refs/heads/main
```

Untersuchen mit *tree*

```bash
└── refs
    ├── heads   <<< kein "main"
    └── tags
```

--- 

Auf der Client-Seite 

```bash
git clone benutzer@<IP>:/home/benutzer/labor
```

Untersuchen
```bash
tree labor/.git 

# oder 
cd labor/.git
tree
```

--- 

Aktueller Stand

```bash
cat labor/.git/HEAD 

# Ausgabe
ref: refs/heads/master   <<<< trotz "main" auf dem Server
```

```bash
...
└── refs
    ├── heads  <<<<<< Kein "master", kein "main"
    └── tags
```

---

Der Status zeigt 

```bash
cd /home/benutzer/labor 
git status

# Ausgabe 
Auf Branch master

Noch keine Commits

nichts zu committen (erstellen/kopieren Sie Dateien und benutzen
Sie "git add" zum Versionieren)
```

---

Manuelles Ändern des Eintrags in HEAD wirkt sich direkt aus!

*PROBIEREN*

```bash
nano .git/HEAD
...
strg + o
strg + x
```

---

Branch auf *main* umbenennen ändert nur Eintrag in HEAD 

```bash
git branch -m main 
```

::: {.fragment}
Daten erzeugen

```bash
echo "Test" > Readme 
git add .
git commit -m "test"
```
:::

::: {.fragment}
Mit diesem Commit entsteht der eigentliche Branch:

```bash
tree 

# Ausgabe
...
└── refs
    ├── heads
    │   └── main   <<<<<<< NEU
    └── tags

```
:::


---

DIESER Branch kommt auf den Server:

```bash
git push -u origin main 
```
::: columns 
::: column
Tree-Kontrolle auf dem Client:
```bash
tree 

#Ausgabe
...
└── refs
    ├── heads
    │   └── main
    ├── remotes
    │   └── origin
    │       └── main  <<< /origin/main
    └── tags
```
:::
::: column
Tree-Kontrolle auf dem Server:

```bash 
tree 

# Ausgabe
...
└── refs
    ├── heads
    │   └── main   <<< NEU origin main
    └── tags
```
:::
:::

## Fetch / Pull / Push

---

**Fetch / Pull**

*Fetch* holt die Änderungen des *aktuellen* Branchs ohne sie zu integrieren  

*Pull* führt *Fetch* + *Merge* aus => Dateien in aktueller Version 

---

**Beispiel**  

Längeres Script im Material *pull_fetch.sh*


```{.bash style="max-height:60vh; overflow-y:auto;"}
{{< include material/team/pull_fetch.sh >}}
```

---

**Strategie**  

* Der *main*-Branch sollte tabu für *push* sein.   
* Nur Projekt-Manager mergen in *main*
* Absichern durch Hooks möglich

---

**Die KI sagt**

```bash
cd /path/to/projekt.git/hooks
touch pre-receive
chmod +x pre-receive

### Dateiinhalt von pre-reiceive

#!/bin/bash

while read oldrev newrev refname
do
  if [ "$refname" = "refs/heads/main" ]; then
    echo "Pushes to the main branch are not allowed."
    exit 1
  fi
done

exit 0

```

## Szenario durchspielen

---

Max und Susi arbeiten an einem gemeinsamen Projekt ...

::: {.smaller .inset}
* 2 Terminals öffnen
* Ein Ordner max  (Terminal 1)
* Ein Ordner Susi (Terminal 2)
:::

[ToDo (Übung)]{.smaller}

::: {.smaller .inset}
* Repository auf dem Server erstellen
* Lokal clonen und herrichten
* Push auf Server
:::

---

Susi und Max clonen das Repository

```bash
cd /tmp
git clone benutzer@$IP:/home/benutzer/entfernt.git susi
git clone benutzer@$IP:/home/benutzer/entfernt.git max
```

::: {.fragment}
Status-Check von Susi (Max analog)
```bash
Auf Branch main    <<< das ist der lokale von Susi
Ihr Branch ist auf demselben Stand wie 'origin/main'. <<< Server

nichts zu committen, Arbeitsverzeichnis unverändert
```
:::


---

Susi erstellt einen Commit

```bash
echo "Hallo Welt" >> datei_susi.txt
git add datei_susi.txt
git commit -m "Hallo von Susi"
```

Kontrolle
```bash
git Status

# Ausgabe
Auf Branch main
Ihr Branch ist 1 Commit vor 'origin/main'.
(benutzen Sie "git push", um lokale Commits zu publizieren)
nichts zu committen, Arbeitsverzeichnis unverändert
```
---

## Blick in den Tree?

---

Push durch Susi

```bash
git push  
```
*Git* kommentiert das:

```bash
Objekte aufzählen: 4, fertig.
Zähle Objekte: 100% (4/4), fertig.
Delta-Kompression verwendet bis zu 6 Threads.
Komprimiere Objekte: 100% (2/2), fertig.
Schreibe Objekte: 100% (3/3), 292 Bytes | 292.00 KiB/s, fertig.
Gesamt 3 (Delta 0), Wiederverwendet 0 (Delta 0), 
Pack wiederverwendet 0
To /tmp/labor2/entfernt
   d46681d..78db34e  main -> main
``` 

---

Status:

```bash
Auf Branch main                                        <<<< SUSI
Ihr Branch ist auf demselben Stand wie 'origin/main'.  <<<< SERVER 

nichts zu committen, Arbeitsverzeichnis unverändert
```

---

Max beginnt mit der Arbeit

```bash
git fetch   # pull würde gleich auch mergen
```

Als Ausgabe bekommt er
```bash
remote: Objekte aufzählen: 4, fertig.
remote: Zähle Objekte: 100% (4/4), fertig.
remote: Komprimiere Objekte: 100% (2/2), fertig.
remote: Gesamt 3 (Delta 0), Wiederverwendet 0 (Delta 0), 
Pack wiederverwendet 0
Entpacke Objekte: 100% (3/3), 272 Bytes | 272.00 KiB/s, fertig.
Von /tmp/labor2/entfernt
   d46681d..78db34e  main       -> origin/main
```

---

Aktueller Status

```bash
Auf Branch main     <<<< MAX lokal 
Ihr Branch ist 1 Commit hinter 'origin/main', und kann vorgespult 
werden.
(benutzen Sie "git pull", um Ihren lokalen Branch zu aktualisieren)

nichts zu committen, Arbeitsverzeichnis unverändert
```

---

Genauerer Blick

```bash
git log origin/main
```

Max sieht den Commit, der noch nicht in seinen Branch integriert ist.

```bash
commit 78db34e31.....c06aa4dda5c50cdb (origin/main, origin/HEAD)
Author: susi <susi@t-online.de>
Date:   Wed Jan 29 12:39:38 2025 +0100

    Begrüßung

commit d46681db23c9e2b3f5379a951c026e3d673fe3e0 (HEAD -> main)
Author: max <max@t-online.de>
Date:   Wed Jan 29 12:34:48 2025 +0100

    Init
```

---

Sieht ok aus ...

```bash
git merge
```

Die Hashes zeigen, was passiert:

```bash
Aktualisiere d46681d..78db34e
Fast-forward
 datei.txt | 1 +
 1 file changed, 1 insertion(+)
 create mode 100644 datei.txt
```

---

## Wie sieht ein Feher aus?
[Führe das Script *susi_und_max.sh* aus dem Material aus]{.smaller}

---

Susi erstellt einen Commit

```bash
echo "Hallo Welt" >> datei_susi.txt
git add datei_susi.txt
git commit -m "Hallo von Susi"
git push
```

::: {.fragment}
Max erstellt einen Commit (ohne voheriges pullen)
```bash
echo "Hallo Welt" >> datei_max.txt
git add datei_max.txt
git commit -m "Hallo von Max"
```
:::

---

Max versucht einen Push

```bash
To 192.168.3.154:/home/benutzer/entfernt.git
 ! [rejected]        main -> main (fetch first)
error: Fehler beim Versenden einiger Referenzen 
        nach '192.168.3.154:/home/benutzer/entfernt.git'
Hinweis: Updates were rejected because the remote contains work 
Hinweis: that you do not have locally. This is usually caused
Hinweis: by another repository pushing to the same ref. 
Hinweis: If you want to integrate the remote changes, use
Hinweis: 'git pull' before pushing again.
Hinweis: See the 'Note about fast-forwards' in 'git push --help' 
Hinweis: for details.
```

---

Max holt die Änderungen im Repository

```bash
git fetch 
```

Er checkt die Unterschiede

::: {.fragment}
```bash
git log origin/main
git diff main origin/main 
git log HEAD..origin/main 
```
:::

::: {.fragment}
Alles ok

```bash
git merge 
```
:::





