---
title: "Server-Installation"
author: "Wolfgang Höfer"
format: 
  revealjs:
    width: 1300
    margin: 0.05
    auto-stretch: false
jupyter: python3
---

# Allgemein

---

**Varianten**  

* VirtualBox
* Direkt auf dem Server (nicht empfohlen)
* Mit Docker virtualisieren (empfohlen)
* Codeberg.org (selber testen)
* Provider verwenden (kostet mehr)
* Originäre Plattformen gitlab / github / ...

---

**Vorüberlegungen**  

* Zweck des Servers 
* Nutzer des Servers
* Rollen der Benutzer
* Benutzerkonten

::: {.notes}

* Nur git oder mehr
* Weitere Admins im Haus?
* Benutzer nur für Git oder full featured?
* Benamungsprobleme, Doppelungen, Sonderzeichen, ...

:::

---

**VirtualBox**  
Nur für *in Klasse Szenarien* geeignet  
Nicht für Server im Internet

---

**Vollwertiger Server**  

* Simulieren wir hier mit Proxmox  
* Jeder bekommt einen kompletten Server -- virtuell

---

**Docker**  

* Simulieren wir mit Proxmox
* Jeder bekommt einen kompletten Server -- virtuell

# Git-Server -- native

## Verbindung zum Server

Für die Installation ssh-Verbindung nötig

* cmd.exe (nicht empfohlen)
* git-Bash (empfohlen)
* putty (geht auch gut, weil portabel)

---

**ssh**

```bash
ssh benutzer_<x>@<IP-Trainingsserver>
```

Rückmeldung:  

```bash
The authenticity of host 'try.example.com (38.243.220.195)' can't be established.
ED25519 key fingerprint is SHA256:DSeSsfXDL2PkSlLYCt64krg9xa2vNr3og5SBJzZ/WNk.
This key is not known by any other names.
Are you sure you want to continue connecting (yes/no/[fingerprint])?
```

Bestätigen mit *yes*

Kennwort *gitkurs* (evtl. keine Anzeige am Bildschirm)

---

**logout**

* exit
* logout
* strg+d
* schließen (brutale Variante)

---

**Kennwortlosen Zugang einrichten**

```bash
# git-bash
ssh-keygen -t rsa
```
Alle Fragen mit ENTER quittieren

---

**Kennwortlosen Zugang einrichten**

Anzeigen des Keys:
```bash
cat .ssh/id_rsa.pub
```

Markieren & Kopieren mit rechter Maustaste

---

**Kennwortlosen Zugang einrichten**

Anmelden als Benutzer *benutzer* 
auf dem Server:

```bash
ssh -p benutzer@<ip-Eigener-Server>
```

Rückmeldung:
```bash
The authenticity of host 'try.example.com (38.243.220.195)' can't be established.
ED25519 key fingerprint is SHA256:DSeSsfXDL2PkSlLYCt64krg9xa2vNr3og5SBJzZ/WNk.
This key is not known by any other names.
Are you sure you want to continue connecting (yes/no/[fingerprint])?
```

Warnung mit *yes* quittieren  
Kennwort *gitkurs* eingeben (evtl. keine Anzeige am Bildschirm)

---

**Kennwortlosen Zugang einrichten**

Eintragen des Keys:

```bash
mkdir .ssh
nano .ssh/authorized_keys
# rechte Maustaste einfügen
# strg + o
# strg + x
chmod 644 .ssh/authorized_keys
```

---

**Kennwortlosen Zugang einrichten**

Abmelden und neu anmelden. Sollte jetzt ohne Kennwort klappen.

---

**Individuelle Nutzer (=Schüler)**

Im Prinzip muss der Schlüssel für jeden Benutzer eingetragen werden.


---

**Server aktualisieren**

```bash
sudo -i 
# Kennwort gitkurs 
apt update 
apt upgrade
```

---

**Installieren von git**

```bash
apt install git -y
# eventuell noch 
apt install gitk git-big-picture
```

---

**Anlegen von Benutzern**

Je nach Einsatzzweck des Servers verschieden

---

**Anlegen von Benutzern**

```bash
adduser max
```

---

**Scripting**

```bash
#!/bin/bash

PASSWORT="gitkurs"

for i in {1..30}; do
  USER="benutzer_$i"
  useradd -m "$USER"
  echo "$USER:$PASSWORT" | chpasswd
done
```

---

**Aufgabe**  

Lege einen Benutzer *git* mit Kennwort *Unterricht* an

---

**Repository vorbereiten**

```bash
groupadd gitklasse
usermod -aG gitklasse benutzer_1
mkdir -p /srv/git/klasse.git
cd /srv/git/klasse.git
git init --bare 
git branch -m main 
chown -R root:gitklasse /srv/git/klasse.git
chmod -R 2770 /srv/git/klasse.git
```

# Git-Server mit Docker

## Was ist Docker?

* Spezielle Virtualisierungslösung
* Verwendet laufendes System mit  
* ergänzt schichtweise fehlende Komponenten
* Komplette Systeme mit einem Befehl erstellen

---

**Installation**  

* Anmelden auf Server
* sudo -i 
* Installationsscript ausführen

---

**Script**  

```bash
sudo -i
apt update
apt install apt-transport-https curl -y
curl -fsSL https://download.docker.com/linux/ubuntu/gpg
| gpg --dearmor -o /etc/apt/keyrings/docker.gpg
\
echo "deb [arch=$(dpkg --print-architecture) \
signed-by=/etc/apt/keyrings/docker.gpg] \
https://download.docker.com/linux/ubuntu \
$(. /etc/os-release && echo "$VERSION_CODENAME") \
stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
```

---

**Script**  

```bash
apt update
apt install docker-ce docker-ce-cli \
containerd.io docker-buildx-plugin \
docker-compose-plugin -y
compose_url="https://github.com/docker/compose/releases/download"
curl -L $compose_url/1.28.5/docker-compose-`uname \
-s`-`uname -m` -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
```

---

**Test der Installation**

```bash
docker --version
docker-compose --version
```

---

**Varianten**  

* Direkter Aufruf mit allen Parametern.
* Mit Dockerfile die Einstellungen für das Image zusammenfassen.  
  Immer noch viele Einstellungen über Kommandozeile.
* Mit Docker-Compose den kompletten Aufruf managen und auch
  mehrere Container verwalten.

---

**Erster Kontakt**  

```bash
docker run -d -p 8090:80 --name it-tools corentinth/it-tools
```

* `-d` = Als Hintergrunddienst
* `-p 8090:80` = Die Software verwendet Port 80, ist aber über 8090 erreichbar
* `--name` = So taucht der Container in der Liste auf
* `corentinth/it-tools` Image

---

**Erster Kontakt**

Aufruf im Browser

```bash
http://<IP>:8090
```

... Spielen !

---

**Was ist passiert**  

```bash
# Container-Info
docker ps  
# docker ps -a 
```

```bash
# Image-Info
docker image ls 
```

---

|Befehl|Wirkung|
|------|-------|
|docker stop it-tools| Container stoppen|
|docker stop bd072e349cab| geht auch|
|docker start it-tools|Container starten|
|docker start bd072e349cab| geht auch|
|docker rm it-tools|Container entfernen -- Image bleibt!|
|docker rmi "corentinth/it-tools"|Entfernt auch das Image|

---

**Aufräumen**

```bash
# gestoppte Container löschen
docker rm <hash> # oder Name

# Laufenden Container löschen (brutale Variante)
docker rm -f <hash>

# Image löschen 
docker rmi <hash>

```

Image ist nur löschbar, wenn kein zugehöriger Container existiert. 

---

**Weitere Schritte**  

* Die Parameter in einem Dockerfile zusammenfassen
* Organisieren von Containern in Docker-Compose Files

---

**Einfaches Dockerfile**

* Welches Image 
* Welche Programme
* Arbeitsverzeichnis im Container (z.B. /app) 
* Copier-Befehl für Arbeitsdateien (copy . /app)
* Erweitertes Copy = Add (z.B. Entpacken im Container)
* Startbefehl für laufenden Container (CMD)
* Alternativ *ENTRYPOINT*
* Verwendete Shell (SHELL["bin/bash", "-c"])
* Mountpoints für Volumes (VOLUME["/pfad/im/container"])
* Benutzer (USER appuser)

---

**Container erstellen und starten**

Einfaches Dockerfile

```bash
FROM lighttpd:latest
# Kein Latest bei "ernsten" Projekten

# Config ersetzen
COPY lighttpd.conf /etc/lighttpd/lighttpd.conf

# Website kopieren
COPY index.html /var/www/html/index.html

# Nur Doku
EXPOSE 80

CMD ["lighttpd", "-D", "-f", "/etc/lighttpd/lighttpd.conf"]

```

---

**Container erstellen und starten**

```bash
# Image erstellen
docker build -t meinWebserver .  # Punkt wichtig

# Container starten 
docker run --rm -p 8080:80 meinWebserver
```

---

**Lighttp komplexer**

Dockerfile
```bash
```
---

**Lighttp komplexer**

---

**Lighttp komplexer**

---

**Lighttp komplexer**

---
xxx

---

**Problem**

Bei mehreren Containern, die zusammenarbeiten sind 
Abhängigkeiten schwer zu verwalten -> Docker compose

---

**Komplexeres Dockerfile**  

```bash
FROM ubuntu:24.04
     
# Installiere Git und Nginx
RUN apt-get update && apt-get install -y \
    git \
    nginx \
    && rm -rf /var/lib/apt/lists/*

# Erstelle Git-Repositorys
RUN mkdir -p ./repositories

# Kopiere das Nginx-Config
COPY nginx.conf /etc/nginx/nginx.conf

# Kopiere Beispiel-Repositories (optional)
RUN mkdir ./repositories/myrepo.git && \
          ./repositories/myrepo.git && \
          git init --bare

# Nginx- und Git-Ports freigeben
EXPOSE 80 9418

# Starte nginx
CMD ["nginx", "-g", "daemon off;"]
```

---


**Docker compose**

* Yaml-Steuerungsdatei zum Koordinieren von mehreren Containern
* Definiert Abhängigkeiten zwischen Containern
* Definiert eigene Netzwerke für Container.

---

**Übungen**

---
